import React from 'react';
import { Info } from 'lucide-react';
import { getAgentIcon, getComplexityColor } from '../utils/helpers';

const ResultTab = ({ result }) => {
  const AgentIcon = getAgentIcon(result.candidate.source_agent);

  return (
    <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-purple-500/20">
      {/* Agent Info */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-purple-600/20 rounded-xl">
            <AgentIcon className="w-8 h-8 text-purple-300" />
          </div>
          <div>
            <p className="text-sm text-purple-300">Generated by</p>
            <p className="text-xl font-bold text-white">
              {result.candidate.source_agent} Agent
            </p>
          </div>
        </div>
        <div className={`px-4 py-2 rounded-lg font-semibold ${getComplexityColor(result.candidate.complexity_level)}`}>
          {result.candidate.complexity_level} Complexity
        </div>
      </div>

      {/* Command Display */}
      <div className="bg-gray-900 rounded-xl p-6 mb-6 border border-gray-700">
        <div className="flex items-center justify-between mb-3">
          <span className="text-sm font-semibold text-purple-300">Generated Command</span>
          <button
            onClick={() => navigator.clipboard.writeText(result.candidate.command)}
            className="text-sm text-purple-400 hover:text-purple-300"
          >
            Copy
          </button>
        </div>
        <code className="text-green-400 font-mono text-lg block">
          {result.candidate.command}
        </code>
      </div>

      {/* Rationale */}
      <div className="bg-white/5 rounded-xl p-6">
        <div className="flex items-center gap-2 mb-3">
          <Info className="w-5 h-5 text-blue-400" />
          <h3 className="font-semibold text-white">Rationale</h3>
        </div>
        <p className="text-purple-200 leading-relaxed">
          {result.candidate.rationale}
        </p>
      </div>
    </div>
  );
};

export default ResultTab;